<a href="https://colab.research.google.com/github/mf2056/F20AA_CW2/blob/main/Step4%265.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
!pip install -U scikeras scikit-learn

Collecting scikeras
  Downloading scikeras-0.13.0-py3-none-any.whl.metadata (3.1 kB)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (11 kB)
Requirement already satisfied: keras>=3.2.0 in /usr/local/lib/python3.12/dist-packages (from scikeras) (3.13.2)
Requirement already satisfied: numpy>=1.24.1 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.10.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from keras>=3.2.0->scikeras) (1.4.0)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.2.0->scikeras) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.2.0->scikeras) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (from keras>=3.2.0->scikeras) (3.16.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.2.0->scikeras) (0.19.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from keras>=3.2.0->scikeras) (0.5.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from keras>=3.2.0->scikeras) (26.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from optree->keras>=3.2.0->scikeras) (4.15.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.2.0->scikeras) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.2.0->scikeras) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.2.0->scikeras) (0.1.2)
Downloading scikeras-0.13.0-py3-none-any.whl (26 kB)
Downloading scikit_learn-1.8.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (8.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 24.1 MB/s eta 0:00:00
Installing collected packages: scikit-learn, scikeras
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.6.1
    Uninstalling scikit-learn-1.6.1:
      Successfully uninstalled scikit-learn-1.6.1
Successfully installed scikeras-0.13.0 scikit-learn-1.8.0

In [3]:
train = pd.read_csv("/content/drive/MyDrive/train_processed.csv")

train.head()

,text,rating,tokens,stemmed,lemmatized,text_stem,text_lemma,review_length
0,this place is terrible the people in charge ar...,2,"['place', 'terrible', 'people', 'charge', 'wor...","['place', 'terribl', 'peopl', 'charg', 'worst'...","['place', 'terrible', 'people', 'charge', 'wor...",place terribl peopl charg worst part far yeah ...,place terrible people charge worst part far ye...,97
1,terrible service and they are saying that i ne...,1,"['terrible', 'service', 'saying', 'never', 'us...","['terribl', 'servic', 'say', 'never', 'use', '...","['terrible', 'service', 'saying', 'never', 'us...",terribl servic say never use servic lie call n...,terrible service saying never used service lie...,48
2,absolutely terrible company they sent me to co...,1,"['absolutely', 'terrible', 'company', 'sent', ...","['absolut', 'terribl', 'compani', 'sent', 'col...","['absolutely', 'terrible', 'company', 'sent', ...",absolut terribl compani sent collect without a...,absolutely terrible company sent collection wi...,211
3,to find it either park in front of the tuesday...,4,"['find', 'either', 'park', 'front', 'tuesday',...","['find', 'either', 'park', 'front', 'tuesday',...","['find', 'either', 'park', 'front', 'tuesday',...",find either park front tuesday morn mall entra...,find either park front tuesday morning mall en...,66
4,mall location used their services for sedan ni...,4,"['mall', 'location', 'used', 'services', 'seda...","['mall', 'locat', 'use', 'servic', 'sedan', 'n...","['mall', 'location', 'used', 'service', 'sedan...",mall locat use servic sedan nice perhap inform...,mall location used service sedan nice perhaps ...,28

In [4]:
import pandas as pd
import numpy as np

from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV

from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.metrics import classification_report

In [6]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier

In [5]:
train.isnull().sum()

text              43
rating             0
tokens             0
stemmed            0
lemmatized         0
text_stem        105
text_lemma       105
review_length      0
dtype: int64

In [6]:
train["text_lemma"] = train["text_lemma"].fillna("")
train["text_lemma"] = train["text_lemma"].astype(str)

train["text_stem"] = train["text_stem"].fillna("")
train["text_stem"] = train["text_stem"].astype(str)

train["text"] = train["text"].fillna("")
train["text"] = train["text"].astype(str)

X_d = train["text"]
X = train["text_lemma"]
x = train["text_stem"]
Y = train["rating"]

In [7]:
train.shape

(288000, 8)

In [8]:
train.isnull().sum()

text             0
rating           0
tokens           0
stemmed          0
lemmatized       0
text_stem        0
text_lemma       0
review_length    0
dtype: int64

In [9]:
import pandas as pd
from sklearn.model_selection import GridSearchCV

def run_gridsearch(name, pipeline, params):
    # 1. Define multiple metrics
    scoring = {
        'Accuracy': 'accuracy',
        'MacroF1': 'f1_macro'
    }

    grid = GridSearchCV(
        pipeline,
        params,
        cv=3,
        n_jobs=-1,
        verbose=1,
        scoring=scoring,
        refit='MacroF1',
        return_train_score=False
    )

    grid.fit(X, Y)

    # 2. Extract detailed results into a table
    results_df = pd.DataFrame(grid.cv_results_)

    # Select columns for the 3 folds and the means
    columns_to_show = ['params']
    # Add Accuracy columns
    columns_to_show += ['split0_test_Accuracy', 'split1_test_Accuracy', 'split2_test_Accuracy', 'mean_test_Accuracy']
    # Add F1 columns
    columns_to_show += ['split0_test_MacroF1', 'split1_test_MacroF1', 'split2_test_MacroF1', 'mean_test_MacroF1']

    report_table = results_df[columns_to_show].sort_values('mean_test_MacroF1', ascending=False)

    print(f"\n==== {name} DETAILED FOLD RESULTS ====")
    print(report_table.to_string(index=False))

    # 3. Print the absolute bests
    best_f1_idx = results_df['mean_test_MacroF1'].idxmax()
    best_acc_idx = results_df['mean_test_Accuracy'].idxmax()

    print(f"\n--- {name} Summary ---")
    print(f"Best Params (for F1): {grid.best_params_}")
    print(f"Best Mean Macro-F1: {results_df.loc[best_f1_idx, 'mean_test_MacroF1']:.4f}")
    print(f"Best Mean Accuracy: {results_df.loc[best_acc_idx, 'mean_test_Accuracy']:.4f}")

    return grid

In [49]:
nb_pipeline = Pipeline([
    ("tfidf", TfidfVectorizer()),
    ("clf", MultinomialNB())
])

nb_params = {
    "clf__alpha": [0.1, 0.5, 1.0],
    "tfidf__ngram_range": [(1, 1), (1, 2)],
    "tfidf__max_features": [10000, 20000, 50000]
}

nb_grid = run_gridsearch(
    "Naive Bayes",
    nb_pipeline,
    nb_params
)

Fitting 3 folds for each of 18 candidates, totalling 54 fits

==== Naive Bayes DETAILED FOLD RESULTS ====
                                                                         params  split0_test_Accuracy  split1_test_Accuracy  split2_test_Accuracy  mean_test_Accuracy  split0_test_MacroF1  split1_test_MacroF1  split2_test_MacroF1  mean_test_MacroF1
{'clf__alpha': 0.1, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.637219              0.636490              0.635531            0.636413             0.465647             0.465948             0.465692           0.465763
{'clf__alpha': 0.1, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.635490              0.634865              0.634031            0.634795             0.455449             0.456240             0.457453           0.456381
{'clf__alpha': 0.5, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.635573              0.634500              0.634583            0.634885             0.445423             0.445651             0.448154           0.446409
{'clf__alpha': 0.1, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.632854              0.632146              0.631437            0.632146             0.445820             0.444637             0.446276           0.445577
{'clf__alpha': 0.5, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.636573              0.636625              0.635854            0.636351             0.439673             0.441473             0.441371           0.440839
{'clf__alpha': 0.5, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.632927              0.632094              0.631031            0.632017             0.440881             0.439504             0.440533           0.440306
{'clf__alpha': 1.0, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.631896              0.631344              0.630406            0.631215             0.432682             0.432268             0.433018           0.432656
{'clf__alpha': 1.0, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.634240              0.632927              0.633563            0.633576             0.430371             0.430254             0.432765           0.431130
{'clf__alpha': 0.1, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.619062              0.616781              0.616500            0.617448             0.416855             0.415051             0.415831           0.415913
{'clf__alpha': 0.1, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.620729              0.618469              0.618281            0.619160             0.414511             0.413304             0.413827           0.413881
{'clf__alpha': 0.1, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.615271              0.614135              0.612521            0.613976             0.411389             0.410384             0.409313           0.410362
{'clf__alpha': 0.5, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.620448              0.618500              0.618010            0.618986             0.408476             0.407876             0.408146           0.408166
{'clf__alpha': 1.0, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.632010              0.629823              0.629906            0.630580             0.405300             0.404131             0.404143           0.404525
{'clf__alpha': 0.5, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.617854              0.616833              0.615917            0.616868             0.400975             0.400758             0.401206           0.400980
{'clf__alpha': 1.0, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.618938              0.617302              0.617260            0.617833             0.399454             0.398902             0.400169           0.399509
{'clf__alpha': 1.0, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.612792              0.612625              0.611698            0.612372             0.378080             0.379572             0.379128           0.378927
{'clf__alpha': 0.5, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.609052              0.608615              0.606156            0.607941             0.365782             0.366203             0.363655           0.365214
{'clf__alpha': 1.0, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.598656              0.597427              0.596281            0.597455             0.325537             0.325276             0.323934           0.324916

--- Naive Bayes Summary ---
Best Params (for F1): {'clf__alpha': 0.1, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}
Best Mean Macro-F1: 0.4658
Best Mean Accuracy: 0.6364

In [51]:
lr_pipeline = Pipeline([
    ("tfidf", TfidfVectorizer()),
    ("clf", LogisticRegression(max_iter=1000))
])

lr_params = {
    "clf__C": [0.5, 1, 3],
    "tfidf__ngram_range": [(1, 1), (1, 2)],
    "tfidf__max_features": [10000, 20000, 50000]
}

lr_grid = run_gridsearch(
    "Logistic Regression",
    lr_pipeline,
    lr_params
)

Fitting 3 folds for each of 18 candidates, totalling 54 fits

==== Logistic Regression DETAILED FOLD RESULTS ====
                                                                     params  split0_test_Accuracy  split1_test_Accuracy  split2_test_Accuracy  mean_test_Accuracy  split0_test_MacroF1  split1_test_MacroF1  split2_test_MacroF1  mean_test_MacroF1
  {'clf__C': 3, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.647729              0.647885              0.648146            0.647920             0.510176             0.509683             0.511105           0.510321
  {'clf__C': 3, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.651542              0.649958              0.650062            0.650521             0.510756             0.508212             0.511439           0.510136
  {'clf__C': 3, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.646333              0.646010              0.646323            0.646222             0.508253             0.508825             0.512554           0.509877
  {'clf__C': 1, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.657448              0.655427              0.654552            0.655809             0.505192             0.501824             0.504632           0.503882
  {'clf__C': 1, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.656573              0.654563              0.654302            0.655146             0.503656             0.500752             0.505162           0.503190
  {'clf__C': 1, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.657469              0.655490              0.654615            0.655858             0.503323             0.501926             0.502848           0.502699
  {'clf__C': 3, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.644823              0.643792              0.644146            0.644253             0.498342             0.496925             0.499301           0.498189
  {'clf__C': 3, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.644115              0.643531              0.643615            0.643753             0.496936             0.497387             0.499670           0.497998
  {'clf__C': 3, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.646094              0.645583              0.644802            0.645493             0.498551             0.496668             0.498754           0.497991
{'clf__C': 0.5, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.657469              0.655563              0.654813            0.655948             0.493790             0.491592             0.494944           0.493442
{'clf__C': 0.5, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.658583              0.656563              0.655865            0.657003             0.494891             0.491136             0.494138           0.493388
  {'clf__C': 1, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.650177              0.649583              0.649604            0.649788             0.491135             0.490732             0.493256           0.491708
  {'clf__C': 1, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.650500              0.649188              0.648615            0.649434             0.491710             0.490552             0.491780           0.491348
  {'clf__C': 1, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.650698              0.649500              0.649135            0.649778             0.490955             0.489986             0.492798           0.491246
{'clf__C': 0.5, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.658260              0.655458              0.655844            0.656521             0.489980             0.486335             0.491203           0.489173
{'clf__C': 0.5, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.651698              0.650250              0.649448            0.650465             0.482420             0.480971             0.483125           0.482172
{'clf__C': 0.5, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.651521              0.650010              0.649115            0.650215             0.482588             0.480785             0.483101           0.482158
{'clf__C': 0.5, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.651052              0.650198              0.649635            0.650295             0.480759             0.480178             0.482465           0.481134

--- Logistic Regression Summary ---
Best Params (for F1): {'clf__C': 3, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}
Best Mean Macro-F1: 0.5103
Best Mean Accuracy: 0.6570

In [56]:
svm_pipeline = Pipeline([
    ("tfidf", TfidfVectorizer(
    )),
    ("clf", LinearSVC())
])

svm_params = {
    "clf__C": [0.5, 1, 2],
    "tfidf__ngram_range": [(1, 1), (1, 2)],
    "tfidf__max_features": [10000, 20000, 50000]
}

svm_grid = run_gridsearch(
    "SVM",
    svm_pipeline,
    svm_params
)

Fitting 3 folds for each of 18 candidates, totalling 54 fits

==== SVM DETAILED FOLD RESULTS ====
                                                                     params  split0_test_Accuracy  split1_test_Accuracy  split2_test_Accuracy  mean_test_Accuracy  split0_test_MacroF1  split1_test_MacroF1  split2_test_MacroF1  mean_test_MacroF1
  {'clf__C': 2, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.636646              0.635865              0.636083            0.636198             0.489704             0.489794             0.493818           0.491105
{'clf__C': 0.5, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.644823              0.643312              0.643302            0.643813             0.489808             0.489903             0.493333           0.491014
  {'clf__C': 1, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.632250              0.631396              0.631490            0.631712             0.489493             0.490090             0.492892           0.490825
  {'clf__C': 1, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.642365              0.641927              0.641687            0.641993             0.488896             0.489396             0.493458           0.490583
{'clf__C': 0.5, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.648687              0.646969              0.647375            0.647677             0.486875             0.487073             0.490811           0.488253
  {'clf__C': 2, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.616948              0.615635              0.617083            0.616556             0.485217             0.485928             0.488676           0.486607
  {'clf__C': 2, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.647667              0.645906              0.645969            0.646514             0.486029             0.483722             0.487669           0.485807
  {'clf__C': 1, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.649323              0.647594              0.647479            0.648132             0.484924             0.482709             0.486402           0.484678
{'clf__C': 0.5, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.651396              0.649698              0.649813            0.650302             0.482122             0.480545             0.484496           0.482388
  {'clf__C': 1, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.637156              0.633938              0.635448            0.635514             0.470233             0.467456             0.471438           0.469709
  {'clf__C': 2, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.633677              0.630229              0.631552            0.631819             0.470131             0.466606             0.471551           0.469429
  {'clf__C': 1, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.639573              0.635750              0.636802            0.637375             0.470268             0.466934             0.470884           0.469362
  {'clf__C': 2, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.629271              0.626625              0.627583            0.627826             0.469458             0.466793             0.470447           0.468899
{'clf__C': 0.5, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.643781              0.639719              0.641229            0.641576             0.468633             0.464722             0.469156           0.467504
{'clf__C': 0.5, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.644573              0.640771              0.641906            0.642417             0.468632             0.464587             0.469114           0.467444
  {'clf__C': 2, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.640385              0.636719              0.638219            0.638441             0.467668             0.465065             0.469217           0.467317
  {'clf__C': 1, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.643042              0.639323              0.640677            0.641014             0.467284             0.464643             0.469048           0.466992
{'clf__C': 0.5, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.645906              0.641469              0.642813            0.643396             0.466162             0.461992             0.467239           0.465131

--- SVM Summary ---
Best Params (for F1): {'clf__C': 2, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}
Best Mean Macro-F1: 0.4911
Best Mean Accuracy: 0.6503

In [18]:
from sklearn.linear_model import SGDClassifier

sgd_pipeline = Pipeline([
    ("tfidf", TfidfVectorizer()), # Parameters handled by grid
    ("clf", SGDClassifier(max_iter=1000, tol=1e-3, random_state=25))
])

sgd_params = {
    "clf__alpha": [0.0001, 0.001, 0.01],
    "tfidf__ngram_range": [(1, 1), (1, 2)],
    "tfidf__max_features": [10000,20000, 50000]
}

sgd_grid = run_gridsearch("SGD Classifier", sgd_pipeline, sgd_params)

Fitting 3 folds for each of 18 candidates, totalling 54 fits

==== SGD Classifier DETAILED FOLD RESULTS ====
                                                                            params  split0_test_Accuracy  split1_test_Accuracy  split2_test_Accuracy  mean_test_Accuracy  split0_test_MacroF1  split1_test_MacroF1  split2_test_MacroF1  mean_test_MacroF1
{'clf__alpha': 0.0001, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.635687              0.633729              0.633042            0.634153             0.403259             0.402127             0.403054           0.402813
{'clf__alpha': 0.0001, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.634667              0.632823              0.632656            0.633382             0.399555             0.399090             0.400321           0.399656
{'clf__alpha': 0.0001, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.633646              0.630354              0.630990            0.631663             0.399573             0.397721             0.399907           0.399067
{'clf__alpha': 0.0001, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.633062              0.630156              0.630604            0.631274             0.397773             0.396355             0.398700           0.397609
{'clf__alpha': 0.0001, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.632479              0.629667              0.629719            0.630622             0.396445             0.395405             0.396860           0.396237
{'clf__alpha': 0.0001, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.633292              0.631292              0.630865            0.631816             0.396397             0.395277             0.396479           0.396051
 {'clf__alpha': 0.001, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.594510              0.591865              0.592917            0.593097             0.333135             0.330743             0.331570           0.331816
 {'clf__alpha': 0.001, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.595417              0.592531              0.593021            0.593656             0.329854             0.328127             0.328653           0.328878
 {'clf__alpha': 0.001, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.590313              0.588333              0.589313            0.589319             0.327923             0.326357             0.326819           0.327033
 {'clf__alpha': 0.001, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.594562              0.591073              0.591917            0.592517             0.328565             0.325114             0.326378           0.326685
 {'clf__alpha': 0.001, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.593458              0.590500              0.591219            0.591726             0.325984             0.323622             0.324759           0.324788
 {'clf__alpha': 0.001, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.584979              0.583073              0.584052            0.584035             0.322538             0.321204             0.322364           0.322035
  {'clf__alpha': 0.01, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.571729              0.569104              0.569469            0.570101             0.308391             0.307156             0.307421           0.307656
  {'clf__alpha': 0.01, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.570958              0.567979              0.568958            0.569299             0.307766             0.305729             0.306579           0.306691
  {'clf__alpha': 0.01, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.569958              0.566583              0.568000            0.568181             0.306720             0.304309             0.305503           0.305511
  {'clf__alpha': 0.01, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.566500              0.562656              0.564219            0.564458             0.295936             0.292747             0.293887           0.294190
  {'clf__alpha': 0.01, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.567187              0.563760              0.564740            0.565229             0.295363             0.292582             0.293508           0.293818
  {'clf__alpha': 0.01, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.566948              0.563021              0.564469            0.564812             0.295551             0.292243             0.293432           0.293742

--- SGD Classifier Summary ---
Best Params (for F1): {'clf__alpha': 0.0001, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}
Best Mean Macro-F1: 0.4028
Best Mean Accuracy: 0.6342

In [17]:
from sklearn.linear_model import RidgeClassifier

ridge_pipeline = Pipeline([
    ("tfidf", TfidfVectorizer()),
    ("clf", RidgeClassifier(random_state=28))
])

ridge_params = {
    "tfidf__ngram_range": [(1, 1), (1, 2)],  # Comparison requirement [cite: 39]
    "tfidf__max_features": [10000,20000, 50000],   # Representation requirement [cite: 38]
    "clf__alpha": [0.1, 1.0, 10.0]           # The "knob" for regularization
}

ridge_grid = run_gridsearch("Ridge Classifier", ridge_pipeline, ridge_params)

Fitting 3 folds for each of 18 candidates, totalling 54 fits

==== Ridge Classifier DETAILED FOLD RESULTS ====
                                                                          params  split0_test_Accuracy  split1_test_Accuracy  split2_test_Accuracy  mean_test_Accuracy  split0_test_MacroF1  split1_test_MacroF1  split2_test_MacroF1  mean_test_MacroF1
 {'clf__alpha': 1.0, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.642354              0.640563              0.640708            0.641208             0.476540             0.475902             0.479258           0.477233
 {'clf__alpha': 0.1, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.637708              0.635802              0.637281            0.636931             0.473894             0.472687             0.478457           0.475013
 {'clf__alpha': 1.0, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.645969              0.643875              0.644719            0.644854             0.471287             0.470106             0.475398           0.472264
 {'clf__alpha': 0.1, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.609510              0.607906              0.608927            0.608781             0.469053             0.468478             0.473190           0.470240
 {'clf__alpha': 0.1, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.645167              0.643719              0.643240            0.644042             0.467612             0.465768             0.469419           0.467600
 {'clf__alpha': 1.0, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.647740              0.645760              0.645344            0.646281             0.465441             0.463398             0.467073           0.465304
 {'clf__alpha': 1.0, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.638365              0.635229              0.635333            0.636309             0.451298             0.448372             0.451321           0.450330
 {'clf__alpha': 1.0, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.638958              0.635323              0.636385            0.636889             0.450802             0.446890             0.451201           0.449631
 {'clf__alpha': 0.1, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.636427              0.633938              0.634000            0.634788             0.449452             0.447689             0.450267           0.449136
 {'clf__alpha': 0.1, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.626656              0.623313              0.623698            0.624556             0.450584             0.446941             0.449831           0.449119
{'clf__alpha': 10.0, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.650844              0.648521              0.649250            0.649538             0.448693             0.446113             0.452263           0.449023
{'clf__alpha': 10.0, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.651583              0.649500              0.649104            0.650062             0.448938             0.445682             0.449507           0.448042
 {'clf__alpha': 1.0, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.640781              0.637687              0.637948            0.638806             0.448464             0.445549             0.449217           0.447743
{'clf__alpha': 10.0, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.649177              0.647031              0.647094            0.647767             0.447482             0.445331             0.449296           0.447370
 {'clf__alpha': 0.1, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.614625              0.613260              0.613104            0.613663             0.446330             0.445159             0.446552           0.446014
{'clf__alpha': 10.0, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.644229              0.641083              0.641437            0.642250             0.434886             0.432024             0.435084           0.433998
{'clf__alpha': 10.0, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.644062              0.641906              0.641823            0.642597             0.433774             0.432199             0.434760           0.433577
{'clf__alpha': 10.0, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.644292              0.641708              0.641990            0.642663             0.433480             0.431675             0.434647           0.433267

--- Ridge Classifier Summary ---
Best Params (for F1): {'clf__alpha': 1.0, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}
Best Mean Macro-F1: 0.4772
Best Mean Accuracy: 0.6501

In [10]:
import pandas as pd
from sklearn.model_selection import GridSearchCV

def run_gridsearch(name, pipeline, params):
    # 1. Define multiple metrics
    scoring = {
        'Accuracy': 'accuracy',
        'MacroF1': 'f1_macro'
    }

    grid_st = GridSearchCV(
        pipeline,
        params,
        cv=3,
        n_jobs=-1,
        verbose=1,
        scoring=scoring,
        refit='MacroF1',
        return_train_score=False
    )

    grid_st.fit(x, Y)

    # 2. Extract detailed results into a table
    results_df = pd.DataFrame(grid_st.cv_results_)

    # Select columns for the 3 folds and the means
    columns_to_show = ['params']
    # Add Accuracy columns
    columns_to_show += ['split0_test_Accuracy', 'split1_test_Accuracy', 'split2_test_Accuracy', 'mean_test_Accuracy']
    # Add F1 columns
    columns_to_show += ['split0_test_MacroF1', 'split1_test_MacroF1', 'split2_test_MacroF1', 'mean_test_MacroF1']

    report_table = results_df[columns_to_show].sort_values('mean_test_MacroF1', ascending=False)

    print(f"\n==== {name} DETAILED FOLD RESULTS ====")
    print(report_table.to_string(index=False))

    # 3. Print the absolute bests
    best_f1_idx = results_df['mean_test_MacroF1'].idxmax()
    best_acc_idx = results_df['mean_test_Accuracy'].idxmax()

    print(f"\n--- {name} Summary ---")
    print(f"Best Params (for F1): {grid_st.best_params_}")
    print(f"Best Mean Macro-F1: {results_df.loc[best_f1_idx, 'mean_test_MacroF1']:.4f}")
    print(f"Best Mean Accuracy: {results_df.loc[best_acc_idx, 'mean_test_Accuracy']:.4f}")

    return grid_st

In [11]:
nb_pipeline = Pipeline([
    ("tfidf", TfidfVectorizer()),
    ("clf", MultinomialNB())
])

nb_params = {
    "clf__alpha": [0.1, 0.5, 1.0],
    "tfidf__ngram_range": [(1, 1), (1, 2)],
    "tfidf__max_features": [10000, 20000, 50000]
}

nb_grid = run_gridsearch(
    "Naive Bayes",
    nb_pipeline,
    nb_params
)

Fitting 3 folds for each of 18 candidates, totalling 54 fits

==== Naive Bayes DETAILED FOLD RESULTS ====
                                                                         params  split0_test_Accuracy  split1_test_Accuracy  split2_test_Accuracy  mean_test_Accuracy  split0_test_MacroF1  split1_test_MacroF1  split2_test_MacroF1  mean_test_MacroF1
{'clf__alpha': 0.1, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.635104              0.634896              0.633302            0.634434             0.462244             0.462969             0.462135           0.462449
{'clf__alpha': 0.1, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.633677              0.633135              0.631708            0.632840             0.452543             0.454890             0.453445           0.453626
{'clf__alpha': 0.5, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.634208              0.633521              0.631927            0.633219             0.443532             0.445484             0.443797           0.444271
{'clf__alpha': 0.1, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.631042              0.631417              0.629510            0.630656             0.443206             0.443839             0.442969           0.443338
{'clf__alpha': 0.5, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.631115              0.631417              0.628979            0.630503             0.438542             0.439160             0.437451           0.438385
{'clf__alpha': 0.5, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.635031              0.634500              0.633729            0.634420             0.437169             0.438589             0.438248           0.438002
{'clf__alpha': 1.0, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.630313              0.630292              0.628375            0.629660             0.430826             0.430817             0.430176           0.430606
{'clf__alpha': 1.0, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.632333              0.631375              0.630031            0.631247             0.427538             0.428481             0.427675           0.427898
{'clf__alpha': 0.1, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.615771              0.614635              0.614406            0.614938             0.407927             0.406717             0.407688           0.407444
{'clf__alpha': 0.1, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.613448              0.611979              0.612021            0.612483             0.408973             0.406032             0.407324           0.407443
{'clf__alpha': 1.0, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.630135              0.628052              0.628229            0.628806             0.402288             0.402125             0.401732           0.402048
{'clf__alpha': 0.5, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.614906              0.614031              0.613969            0.614302             0.401261             0.399212             0.400976           0.400483
{'clf__alpha': 0.1, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.609260              0.608865              0.608208            0.608778             0.400868             0.399032             0.399094           0.399665
{'clf__alpha': 1.0, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.613135              0.612281              0.612062            0.612493             0.391364             0.389152             0.390630           0.390382
{'clf__alpha': 0.5, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.611073              0.611365              0.610802            0.611080             0.390158             0.389681             0.390351           0.390064
{'clf__alpha': 1.0, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.606271              0.606750              0.605781            0.606267             0.367069             0.368280             0.366821           0.367390
{'clf__alpha': 0.5, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.601781              0.602365              0.600469            0.601538             0.353426             0.354557             0.352029           0.353337
{'clf__alpha': 1.0, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.590625              0.591271              0.588260            0.590052             0.313202             0.315247             0.311504           0.313317

--- Naive Bayes Summary ---
Best Params (for F1): {'clf__alpha': 0.1, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}
Best Mean Macro-F1: 0.4624
Best Mean Accuracy: 0.6344

In [12]:
lr_pipeline = Pipeline([
    ("tfidf", TfidfVectorizer()),
    ("clf", LogisticRegression(max_iter=1000))
])

lr_params = {
    "clf__C": [0.5, 1, 3],
    "tfidf__ngram_range": [(1, 1), (1, 2)],
    "tfidf__max_features": [10000, 20000, 50000]
}

lr_grid = run_gridsearch(
    "Logistic Regression",
    lr_pipeline,
    lr_params
)

Fitting 3 folds for each of 18 candidates, totalling 54 fits

==== Logistic Regression DETAILED FOLD RESULTS ====
                                                                     params  split0_test_Accuracy  split1_test_Accuracy  split2_test_Accuracy  mean_test_Accuracy  split0_test_MacroF1  split1_test_MacroF1  split2_test_MacroF1  mean_test_MacroF1
  {'clf__C': 3, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.648135              0.647312              0.648052            0.647833             0.508969             0.509497             0.512469           0.510312
  {'clf__C': 3, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.650583              0.650031              0.649719            0.650111             0.509923             0.508295             0.512018           0.510079
  {'clf__C': 3, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.645531              0.644292              0.644469            0.644764             0.507390             0.507603             0.509176           0.508056
  {'clf__C': 1, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.655698              0.655354              0.654573            0.655208             0.502963             0.502819             0.505395           0.503725
  {'clf__C': 1, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.655552              0.655219              0.654948            0.655240             0.502766             0.501769             0.505989           0.503508
  {'clf__C': 1, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.655594              0.655448              0.654229            0.655090             0.501503             0.500588             0.503513           0.501868
  {'clf__C': 3, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.644208              0.643333              0.642583            0.643375             0.494728             0.495457             0.496178           0.495454
  {'clf__C': 3, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.644656              0.644365              0.643510            0.644177             0.494787             0.494155             0.496218           0.495053
  {'clf__C': 3, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.643823              0.642750              0.641427            0.642667             0.494658             0.494451             0.495286           0.494799
{'clf__C': 0.5, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.655667              0.655271              0.655052            0.655330             0.492725             0.491647             0.495561           0.493311
{'clf__C': 0.5, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.656687              0.655583              0.655979            0.656083             0.491178             0.490965             0.495955           0.492699
{'clf__C': 0.5, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.656656              0.655062              0.655823            0.655847             0.488961             0.487875             0.492260           0.489699
  {'clf__C': 1, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.649375              0.648073              0.647198            0.648215             0.490083             0.488090             0.489471           0.489215
  {'clf__C': 1, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.648813              0.648188              0.646635            0.647878             0.489352             0.487861             0.489655           0.488956
  {'clf__C': 1, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.648594              0.648458              0.646635            0.647896             0.488465             0.488918             0.488900           0.488761
{'clf__C': 0.5, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.649687              0.647948              0.647917            0.648517             0.481816             0.479195             0.481935           0.480982
{'clf__C': 0.5, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.650219              0.648000              0.647198            0.648472             0.482845             0.478748             0.480362           0.480652
{'clf__C': 0.5, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.649646              0.647833              0.647844            0.648441             0.481506             0.477623             0.481383           0.480171

--- Logistic Regression Summary ---
Best Params (for F1): {'clf__C': 3, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}
Best Mean Macro-F1: 0.5103
Best Mean Accuracy: 0.6561

In [13]:
svm_pipeline = Pipeline([
    ("tfidf", TfidfVectorizer(
        ngram_range=(1,2),
        max_features=50000
    )),
    ("clf", LinearSVC())
])

svm_params = {
    "clf__C": [0.5, 1, 2],
    "tfidf__ngram_range": [(1, 1), (1, 2)],
    "tfidf__max_features": [10000, 20000, 50000]
}

svm_grid = run_gridsearch(
    "SVM",
    svm_pipeline,
    svm_params
)

Fitting 3 folds for each of 18 candidates, totalling 54 fits

==== SVM DETAILED FOLD RESULTS ====
                                                                     params  split0_test_Accuracy  split1_test_Accuracy  split2_test_Accuracy  mean_test_Accuracy  split0_test_MacroF1  split1_test_MacroF1  split2_test_MacroF1  mean_test_MacroF1
{'clf__C': 0.5, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.642490              0.641990              0.641740            0.642073             0.488442             0.488397             0.490430           0.489089
  {'clf__C': 1, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.641146              0.640458              0.640687            0.640764             0.487638             0.487635             0.491639           0.488971
  {'clf__C': 2, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.634854              0.633469              0.634781            0.634368             0.487627             0.486734             0.491423           0.488595
  {'clf__C': 1, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.629115              0.630115              0.628792            0.629340             0.487127             0.488678             0.489049           0.488284
{'clf__C': 0.5, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.647229              0.646458              0.646677            0.646788             0.485764             0.485439             0.489923           0.487042
  {'clf__C': 2, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.646729              0.645354              0.645292            0.645792             0.484828             0.482853             0.486762           0.484815
  {'clf__C': 2, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.614271              0.615031              0.614323            0.614542             0.482749             0.484641             0.484868           0.484086
  {'clf__C': 1, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.648573              0.647062              0.647188            0.647608             0.483399             0.482000             0.486160           0.483853
{'clf__C': 0.5, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.650750              0.648948              0.649229            0.649642             0.481324             0.478782             0.484435           0.481514
  {'clf__C': 1, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.636333              0.634625              0.634427            0.635128             0.464561             0.463457             0.466126           0.464714
  {'clf__C': 1, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.637833              0.635698              0.635500            0.636344             0.464763             0.463203             0.465927           0.464631
  {'clf__C': 2, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.632823              0.630115              0.630469            0.631135             0.464859             0.462539             0.466184           0.464527
  {'clf__C': 2, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.630125              0.628333              0.627667            0.628708             0.464322             0.463339             0.465498           0.464386
  {'clf__C': 2, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.638771              0.636375              0.636000            0.637049             0.464460             0.462032             0.465655           0.464049
  {'clf__C': 1, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.641125              0.638687              0.638333            0.639382             0.464046             0.461651             0.464773           0.463490
{'clf__C': 0.5, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.642521              0.639792              0.638656            0.640323             0.463852             0.461902             0.463177           0.462977
{'clf__C': 0.5, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.642375              0.640156              0.638958            0.640497             0.462729             0.461115             0.462885           0.462243
{'clf__C': 0.5, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.643865              0.640865              0.640385            0.641705             0.462308             0.459371             0.462301           0.461327

--- SVM Summary ---
Best Params (for F1): {'clf__C': 0.5, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}
Best Mean Macro-F1: 0.4891
Best Mean Accuracy: 0.6496

In [14]:
from sklearn.linear_model import SGDClassifier

sgd_pipeline = Pipeline([
    ("tfidf", TfidfVectorizer()), # Parameters handled by grid
    ("clf", SGDClassifier(max_iter=1000, tol=1e-3, random_state=25))
])

sgd_params = {
    "clf__alpha": [0.0001, 0.001, 0.01],
    "tfidf__ngram_range": [(1, 1), (1, 2)],
    "tfidf__max_features": [10000, 20000, 50000]
}

sgd_grid = run_gridsearch("SGD Classifier", sgd_pipeline, sgd_params)

Fitting 3 folds for each of 18 candidates, totalling 54 fits

==== SGD Classifier DETAILED FOLD RESULTS ====
                                                                            params  split0_test_Accuracy  split1_test_Accuracy  split2_test_Accuracy  mean_test_Accuracy  split0_test_MacroF1  split1_test_MacroF1  split2_test_MacroF1  mean_test_MacroF1
{'clf__alpha': 0.0001, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.634062              0.633708              0.633646            0.633806             0.402792             0.402921             0.405125           0.403613
{'clf__alpha': 0.0001, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.633542              0.632656              0.632594            0.632931             0.399818             0.400024             0.401631           0.400491
{'clf__alpha': 0.0001, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.631469              0.629448              0.629792            0.630236             0.397889             0.397913             0.400330           0.398711
{'clf__alpha': 0.0001, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.631073              0.628990              0.629406            0.629823             0.396482             0.396579             0.399113           0.397391
{'clf__alpha': 0.0001, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.630875              0.628615              0.628958            0.629483             0.396089             0.396131             0.398066           0.396762
{'clf__alpha': 0.0001, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.631927              0.630812              0.630865            0.631201             0.395621             0.396106             0.397551           0.396426
 {'clf__alpha': 0.001, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.594479              0.592948              0.592646            0.593358             0.333996             0.332436             0.332147           0.332860
 {'clf__alpha': 0.001, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.595760              0.593656              0.593969            0.594462             0.331068             0.329495             0.329562           0.330042
 {'clf__alpha': 0.001, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.594917              0.592865              0.593135            0.593639             0.328526             0.327856             0.327618           0.328000
 {'clf__alpha': 0.001, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.590552              0.588698              0.589625            0.589625             0.328716             0.327426             0.327733           0.327958
 {'clf__alpha': 0.001, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.594448              0.592313              0.592417            0.593059             0.327542             0.326565             0.326017           0.326708
 {'clf__alpha': 0.001, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.584906              0.583875              0.584219            0.584333             0.322888             0.322699             0.322754           0.322780
  {'clf__alpha': 0.01, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.570094              0.567708              0.567865            0.568556             0.307837             0.306904             0.307146           0.307296
  {'clf__alpha': 0.01, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.568802              0.566448              0.567000            0.567417             0.306659             0.304933             0.305721           0.305771
  {'clf__alpha': 0.01, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.567729              0.564792              0.565906            0.566142             0.305540             0.303798             0.304423           0.304587
  {'clf__alpha': 0.01, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.563594              0.560115              0.561187            0.561632             0.292958             0.290205             0.290784           0.291315
  {'clf__alpha': 0.01, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.564458              0.561115              0.561969            0.562514             0.293131             0.289779             0.290760           0.291223
  {'clf__alpha': 0.01, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.564031              0.560333              0.561229            0.561865             0.292834             0.289569             0.290005           0.290803

--- SGD Classifier Summary ---
Best Params (for F1): {'clf__alpha': 0.0001, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}
Best Mean Macro-F1: 0.4036
Best Mean Accuracy: 0.6338

In [15]:
from sklearn.linear_model import RidgeClassifier

ridge_pipeline = Pipeline([
    ("tfidf", TfidfVectorizer()),
    ("clf", RidgeClassifier(random_state=28))
])

ridge_params = {
    "tfidf__ngram_range": [(1, 1), (1, 2)],
    "tfidf__max_features": [10000,20000, 50000],
    "clf__alpha": [0.1, 1.0, 10.0]
}

ridge_grid = run_gridsearch("Ridge Classifier", ridge_pipeline, ridge_params)

Fitting 3 folds for each of 18 candidates, totalling 54 fits

==== Ridge Classifier DETAILED FOLD RESULTS ====
                                                                          params  split0_test_Accuracy  split1_test_Accuracy  split2_test_Accuracy  mean_test_Accuracy  split0_test_MacroF1  split1_test_MacroF1  split2_test_MacroF1  mean_test_MacroF1
 {'clf__alpha': 1.0, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.639781              0.638802              0.639448            0.639344             0.474467             0.473691             0.477435           0.475197
 {'clf__alpha': 0.1, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.637323              0.634938              0.636135            0.636132             0.473857             0.471613             0.477027           0.474166
 {'clf__alpha': 1.0, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.645229              0.643594              0.644542            0.644455             0.470365             0.468759             0.474945           0.471356
 {'clf__alpha': 0.1, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.607000              0.606906              0.606812            0.606906             0.467676             0.468965             0.470280           0.468974
 {'clf__alpha': 0.1, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.644813              0.642698              0.642552            0.643354             0.467866             0.464357             0.468464           0.466896
 {'clf__alpha': 1.0, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.646781              0.644635              0.644938            0.645451             0.464449             0.461149             0.466209           0.463936
{'clf__alpha': 10.0, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 2)}              0.648896              0.647010              0.648115            0.648007             0.446755             0.444433             0.450737           0.447308
{'clf__alpha': 10.0, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}              0.649917              0.648604              0.648427            0.648983             0.446503             0.445455             0.449348           0.447102
{'clf__alpha': 10.0, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 2)}              0.647865              0.645813              0.646531            0.646736             0.446656             0.443557             0.448673           0.446295
 {'clf__alpha': 0.1, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.634333              0.632354              0.630844            0.632510             0.446769             0.445058             0.445700           0.445842
 {'clf__alpha': 1.0, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.636917              0.634042              0.632563            0.634507             0.446754             0.444600             0.444609           0.445321
 {'clf__alpha': 1.0, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.637490              0.634167              0.633667            0.635108             0.446256             0.443615             0.445092           0.444988
 {'clf__alpha': 1.0, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.639177              0.636250              0.634979            0.636802             0.446088             0.442917             0.444422           0.444476
 {'clf__alpha': 0.1, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.624750              0.621833              0.621458            0.622681             0.444633             0.442668             0.443807           0.443703
 {'clf__alpha': 0.1, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.615865              0.615031              0.613010            0.614635             0.441337             0.441175             0.440016           0.440843
{'clf__alpha': 10.0, 'tfidf__max_features': 10000, 'tfidf__ngram_range': (1, 1)}              0.642448              0.640010              0.638563            0.640340             0.432046             0.430555             0.430910           0.431170
{'clf__alpha': 10.0, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 1)}              0.642458              0.640094              0.638833            0.640462             0.431704             0.429988             0.430903           0.430865
{'clf__alpha': 10.0, 'tfidf__max_features': 20000, 'tfidf__ngram_range': (1, 1)}              0.642458              0.640198              0.638885            0.640514             0.431701             0.430050             0.430748           0.430833

--- Ridge Classifier Summary ---
Best Params (for F1): {'clf__alpha': 1.0, 'tfidf__max_features': 50000, 'tfidf__ngram_range': (1, 2)}
Best Mean Macro-F1: 0.4752
Best Mean Accuracy: 0.6490

#Deep Learning models

In [26]:
train['rating'] = train['rating'] - 1

In [27]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Use the ORIGINAL review text here, not stemmed/lemmatized!
max_words = 10000
max_len = 100 # Max words per review

tokenizer = Tokenizer(num_words=max_words)
tokenizer.fit_on_texts(train['text']) # Assuming 'text' is your raw column

sequences = tokenizer.texts_to_sequences(train['text'])
X_seq = pad_sequences(sequences, maxlen=max_len)
y_seq = train['rating'].values # Use the 0-4 labels you fixed earlier

In [28]:
# Create a smaller subset for the BiLSTM (e.g., 50,000 rows)
train_subset = train.sample(n=57000, random_state=20).copy()

# Now use this subset for your Tokenizer and X_seq/y_seq
tokenizer = Tokenizer(num_words=max_words)
tokenizer.fit_on_texts(train_subset['text'])

sequences = tokenizer.texts_to_sequences(train_subset['text'])
X_seq_sub = pad_sequences(sequences, maxlen=max_len)
y_seq_sub = train_subset['rating'].values

In [29]:
import pandas as pd
from sklearn.model_selection import GridSearchCV

def run_gridsearch(name, pipeline, params):
    # 1. Define multiple metrics
    scoring = {
        'Accuracy': 'accuracy',
        'MacroF1': 'f1_macro'
    }

    grid = GridSearchCV(
        pipeline,
        params,
        cv=3,
        n_jobs=-1,
        verbose=1,
        scoring=scoring,
        refit='MacroF1',
        return_train_score=False
    )

    grid.fit(X_seq_sub, y_seq_sub)

    # 2. Extract detailed results into a table
    results_df = pd.DataFrame(grid.cv_results_)

    # Select columns for the 3 folds and the means
    columns_to_show = ['params']
    # Add Accuracy columns
    columns_to_show += ['split0_test_Accuracy', 'split1_test_Accuracy', 'split2_test_Accuracy', 'mean_test_Accuracy']
    # Add F1 columns
    columns_to_show += ['split0_test_MacroF1', 'split1_test_MacroF1', 'split2_test_MacroF1', 'mean_test_MacroF1']

    report_table = results_df[columns_to_show].sort_values('mean_test_MacroF1', ascending=False)

    print(f"\n==== {name} DETAILED FOLD RESULTS ====")
    print(report_table.to_string(index=False))

    # 3. Print the absolute bests
    best_f1_idx = results_df['mean_test_MacroF1'].idxmax()
    best_acc_idx = results_df['mean_test_Accuracy'].idxmax()

    print(f"\n--- {name} Summary ---")
    print(f"Best Params (for F1): {grid.best_params_}")
    print(f"Best Mean Macro-F1: {results_df.loc[best_f1_idx, 'mean_test_MacroF1']:.4f}")
    print(f"Best Mean Accuracy: {results_df.loc[best_acc_idx, 'mean_test_Accuracy']:.4f}")

    return grid

In [30]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Bidirectional, LSTM, Dense, Dropout, Input


def create_bilstm_model(lstm_units=64, dropout_rate=0.2, embedding_dim=100):

    model = Sequential([
        Input(shape=(max_len,)),   # ✅ VERY IMPORTANT

        Embedding(
            input_dim=max_words,
            output_dim=embedding_dim
        ),

        Bidirectional(LSTM(lstm_units)),

        Dropout(dropout_rate),

        Dense(32, activation="relu"),

        Dense(5, activation="softmax")
    ])

    model.compile(
        optimizer="adam",
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"]
    )

    return model

from scikeras.wrappers import KerasClassifier

# Wrap for Scikit-Learn
bilstm_clf = KerasClassifier(
    model=create_bilstm_model,
    verbose=0
)

# Parameters to tune for your "Critical Analysis" [cite: 70]
bilstm_params = {
    "model__lstm_units": [32],
    "model__embedding_dim": [100],
    "batch_size": [64],
    "epochs": [10]
}

bilstm_grid = run_gridsearch("BiLSTM", bilstm_clf, bilstm_params)

Fitting 3 folds for each of 1 candidates, totalling 3 fits

==== BiLSTM DETAILED FOLD RESULTS ====
                                                                                params  split0_test_Accuracy  split1_test_Accuracy  split2_test_Accuracy  mean_test_Accuracy  split0_test_MacroF1  split1_test_MacroF1  split2_test_MacroF1  mean_test_MacroF1
{'batch_size': 64, 'epochs': 10, 'model__embedding_dim': 100, 'model__lstm_units': 32}              0.602421              0.586579              0.590842            0.593281             0.479713              0.48224             0.480069           0.480674

--- BiLSTM Summary ---
Best Params (for F1): {'batch_size': 64, 'epochs': 10, 'model__embedding_dim': 100, 'model__lstm_units': 32}
Best Mean Macro-F1: 0.4807
Best Mean Accuracy: 0.5933

In [32]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Bidirectional, LSTM, Dense, Dropout, Input


def create_bilstm_model(lstm_units=64, dropout_rate=0.2, embedding_dim=100):

    model = Sequential([
        Input(shape=(max_len,)),   # ✅ VERY IMPORTANT

        Embedding(
            input_dim=max_words,
            output_dim=embedding_dim
        ),

        Bidirectional(LSTM(lstm_units)),

        Dropout(dropout_rate),

        Dense(32, activation="relu"),

        Dense(5, activation="softmax")
    ])

    model.compile(
        optimizer="adam",
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"]
    )

    return model

from scikeras.wrappers import KerasClassifier

# Wrap for Scikit-Learn
bilstm_clf = KerasClassifier(
    model=create_bilstm_model,
    verbose=0
)

# Parameters to tune for your "Critical Analysis" [cite: 70]
bilstm_params = {
    "model__lstm_units": [32],
    "model__embedding_dim": [100],
    "batch_size": [64],
    "epochs": [5]
}

bilstm_grid = run_gridsearch("BiLSTM", bilstm_clf, bilstm_params)

Fitting 3 folds for each of 1 candidates, totalling 3 fits

==== BiLSTM DETAILED FOLD RESULTS ====
                                                                               params  split0_test_Accuracy  split1_test_Accuracy  split2_test_Accuracy  mean_test_Accuracy  split0_test_MacroF1  split1_test_MacroF1  split2_test_MacroF1  mean_test_MacroF1
{'batch_size': 64, 'epochs': 5, 'model__embedding_dim': 100, 'model__lstm_units': 32}              0.619579              0.618211              0.603632            0.613807             0.488252             0.499946             0.499348           0.495849

--- BiLSTM Summary ---
Best Params (for F1): {'batch_size': 64, 'epochs': 5, 'model__embedding_dim': 100, 'model__lstm_units': 32}
Best Mean Macro-F1: 0.4958
Best Mean Accuracy: 0.6138

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Bidirectional, LSTM, Dense, Dropout, Input


def create_bilstm_model(lstm_units=64, dropout_rate=0.2, embedding_dim=100):

    model = Sequential([
        Input(shape=(max_len,)),   # ✅ VERY IMPORTANT

        Embedding(
            input_dim=max_words,
            output_dim=embedding_dim
        ),

        Bidirectional(LSTM(lstm_units)),

        Dropout(dropout_rate),

        Dense(32, activation="relu"),

        Dense(5, activation="softmax")
    ])

    model.compile(
        optimizer="adam",
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"]
    )

    return model

from scikeras.wrappers import KerasClassifier

# Wrap for Scikit-Learn
bilstm_clf = KerasClassifier(
    model=create_bilstm_model,
    verbose=0
)

# Parameters to tune for your "Critical Analysis" [cite: 70]
bilstm_params = {
    "model__lstm_units": [64],
    "model__embedding_dim": [100],
    "batch_size": [64],
    "epochs": [5]
}

bilstm_grid = run_gridsearch("BiLSTM", bilstm_clf, bilstm_params)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Bidirectional, LSTM, Dense, Dropout, Input


def create_bilstm_model(lstm_units=64, dropout_rate=0.2, embedding_dim=100):

    model = Sequential([
        Input(shape=(max_len,)),   # ✅ VERY IMPORTANT

        Embedding(
            input_dim=max_words,
            output_dim=embedding_dim
        ),

        Bidirectional(LSTM(lstm_units)),

        Dropout(dropout_rate),

        Dense(32, activation="relu"),

        Dense(5, activation="softmax")
    ])

    model.compile(
        optimizer="adam",
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"]
    )

    return model

from scikeras.wrappers import KerasClassifier

# Wrap for Scikit-Learn
bilstm_clf = KerasClassifier(
    model=create_bilstm_model,
    verbose=0
)

# Parameters to tune for your "Critical Analysis" [cite: 70]
bilstm_params = {
    "model__lstm_units": [128],
    "model__embedding_dim": [100],
    "batch_size": [64],
    "epochs": [5]
}

bilstm_grid = run_gridsearch("BiLSTM", bilstm_clf, bilstm_params)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Bidirectional, LSTM, Dense, Dropout, Input


def create_bilstm_model(lstm_units=64, dropout_rate=0.2, embedding_dim=100):

    model = Sequential([
        Input(shape=(max_len,)),   # ✅ VERY IMPORTANT

        Embedding(
            input_dim=max_words,
            output_dim=embedding_dim
        ),

        Bidirectional(LSTM(lstm_units)),

        Dropout(dropout_rate),

        Dense(32, activation="relu"),

        Dense(5, activation="softmax")
    ])

    model.compile(
        optimizer="adam",
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"]
    )

    return model

from scikeras.wrappers import KerasClassifier

# Wrap for Scikit-Learn
bilstm_clf = KerasClassifier(
    model=create_bilstm_model,
    verbose=0
)

# Parameters to tune for your "Critical Analysis" [cite: 70]
bilstm_params = {
    "model__lstm_units": [32],
    "model__embedding_dim": [200],
    "batch_size": [64],
    "epochs": [5]
}

bilstm_grid = run_gridsearch("BiLSTM", bilstm_clf, bilstm_params)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Bidirectional, LSTM, Dense, Dropout, Input


def create_bilstm_model(lstm_units=64, dropout_rate=0.2, embedding_dim=100):

    model = Sequential([
        Input(shape=(max_len,)),   # ✅ VERY IMPORTANT

        Embedding(
            input_dim=max_words,
            output_dim=embedding_dim
        ),

        Bidirectional(LSTM(lstm_units)),

        Dropout(dropout_rate),

        Dense(32, activation="relu"),

        Dense(5, activation="softmax")
    ])

    model.compile(
        optimizer="adam",
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"]
    )

    return model

from scikeras.wrappers import KerasClassifier

# Wrap for Scikit-Learn
bilstm_clf = KerasClassifier(
    model=create_bilstm_model,
    verbose=0
)

# Parameters to tune for your "Critical Analysis" [cite: 70]
bilstm_params = {
    "model__lstm_units": [64],
    "model__embedding_dim": [200],
    "batch_size": [64],
    "epochs": [5]
}

bilstm_grid = run_gridsearch("BiLSTM", bilstm_clf, bilstm_params)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Bidirectional, LSTM, Dense, Dropout, Input


def create_bilstm_model(lstm_units=64, dropout_rate=0.2, embedding_dim=100):

    model = Sequential([
        Input(shape=(max_len,)),   # ✅ VERY IMPORTANT

        Embedding(
            input_dim=max_words,
            output_dim=embedding_dim
        ),

        Bidirectional(LSTM(lstm_units)),

        Dropout(dropout_rate),

        Dense(32, activation="relu"),

        Dense(5, activation="softmax")
    ])

    model.compile(
        optimizer="adam",
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"]
    )

    return model

from scikeras.wrappers import KerasClassifier

# Wrap for Scikit-Learn
bilstm_clf = KerasClassifier(
    model=create_bilstm_model,
    verbose=0
)

# Parameters to tune for your "Critical Analysis" [cite: 70]
bilstm_params = {
    "model__lstm_units": [128],
    "model__embedding_dim": [200],
    "batch_size": [64],
    "epochs": [5]
}

bilstm_grid = run_gridsearch("BiLSTM", bilstm_clf, bilstm_params)